/**
 * GENERATED by scripts/genPictureBox.ts — do not edit by hand.
 * AI-drawn landmark images (Bedrock Stability) hosted permanently on files.jpc.io.
 * Regenerate with `AWS_PROFILE=personal npx tsx scripts/genPictureBox.ts`. DATA.
 */
export interface PictureBoxSubject {
  display: string;
  accepted: string[];
  hint: string;
  image: string;
}

export const PICTURE_BOX_SUBJECTS: PictureBoxSubject[] = [
  {
    display: 'Eiffel Tower',
    accepted: ['eiffel tower', 'eiffel', 'la tour eiffel'],
    hint: 'Paris, France',
    image: 'https://files.jpc.io/d/b68e52-eiffel-tower.webp',
  },
  {
    display: 'Statue of Liberty',
    accepted: ['statue of liberty', 'lady liberty', 'liberty'],
    hint: 'New York, USA',
    image: 'https://files.jpc.io/d/76eacb-statue-of-liberty.webp',
  },
  {
    display: 'Taj Mahal',
    accepted: ['taj mahal', 'taj'],
    hint: 'Agra, India',
    image: 'https://files.jpc.io/d/9a8afa-taj-mahal.webp',
  },
  {
    display: 'Great Wall of China',
    accepted: ['great wall of china', 'great wall', 'the great wall'],
    hint: 'China',
    image: 'https://files.jpc.io/d/dd89af-great-wall-of-china.webp',
  },
  {
    display: 'Colosseum',
    accepted: ['colosseum', 'coliseum', 'roman colosseum'],
    hint: 'Rome, Italy',
    image: 'https://files.jpc.io/d/474e12-colosseum.webp',
  },
  {
    display: 'Sydney Opera House',
    accepted: ['sydney opera house', 'opera house'],
    hint: 'Sydney, Australia',
    image: 'https://files.jpc.io/d/b2150f-sydney-opera-house.webp',
  },
];
