/** GENERATED by scripts/genQuizFixtures.ts — do not edit by hand. AI-authored
 * CLASSIC quiz, committed so the seed is deterministic. Regenerate with
 * `AWS_PROFILE=personal npm run gen:quiz-fixtures`. DATA (gate-exempt). */
import type { QuizFixture } from './types';

export const classicQuiz: QuizFixture = {
  topic: 'US Presidents of the 2000s',
  categorySlug: 'history',
  description: 'An AI-generated classic quiz.',
  mode: 'CLASSIC',
  inputMode: 'TYPE',
  scoringMode: 'MEMBERSHIP',
  timeLimitSeconds: 120,
  answers: [
    {
      display: 'Bill Clinton',
      accepted: ['Bill Clinton', 'Clinton', 'William Clinton', 'William Jefferson Clinton'],
      promptKind: 'NONE',
    },
    {
      display: 'George W. Bush',
      accepted: ['George W. Bush', 'George Bush', 'Bush', 'George Walker Bush', 'W'],
      promptKind: 'NONE',
    },
    {
      display: 'Barack Obama',
      accepted: ['Barack Obama', 'Obama', 'Barack Hussein Obama'],
      promptKind: 'NONE',
    },
    {
      display: 'Donald Trump',
      accepted: ['Donald Trump', 'Trump', 'Donald J. Trump', 'Donald John Trump'],
      promptKind: 'NONE',
    },
    {
      display: 'Joe Biden',
      accepted: ['Joe Biden', 'Biden', 'Joseph Biden', 'Joseph R. Biden', 'Joseph Robinette Biden'],
      promptKind: 'NONE',
    },
    {
      display: 'Bill Clinton (in office Jan 2000-2001)',
      accepted: ['Bill Clinton (in office Jan 2000-2001)', 'Clinton'],
      promptKind: 'NONE',
    },
  ],
};
