/** GENERATED by scripts/genQuizFixtures.ts — do not edit by hand. AI-authored
 * MULTIPLE_CHOICE quiz, committed so the seed is deterministic. Regenerate with
 * `AWS_PROFILE=personal npm run gen:quiz-fixtures`. DATA (gate-exempt). */
import type { QuizFixture } from './types';

export const multipleChoiceQuiz: QuizFixture = {
  // "Capital Cities" (not "World Capitals") to stay distinct from the featured
  // World Capitals SLIDESHOW game — two identically-named quizzes would make the
  // /quizzes list ambiguous. If regenerating via gen:quiz-fixtures, keep a
  // distinct topic here.
  topic: 'Capital Cities',
  categorySlug: 'geography',
  description: 'An AI-generated multiple choice quiz.',
  mode: 'MULTIPLE_CHOICE',
  inputMode: 'PICK',
  scoringMode: 'MEMBERSHIP',
  timeLimitSeconds: 120,
  answers: [
    {
      display: 'Canberra',
      accepted: ['Canberra'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of Australia?',
      options: ['Canberra', 'Sydney', 'Melbourne', 'Perth'],
    },
    {
      display: 'Ottawa',
      accepted: ['Ottawa'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of Canada?',
      options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    },
    {
      display: 'Tokyo',
      accepted: ['Tokyo'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of Japan?',
      options: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama'],
    },
    {
      display: 'Brasília',
      accepted: ['Brasília'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of Brazil?',
      options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    },
    {
      display: 'Cairo',
      accepted: ['Cairo'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of Egypt?',
      options: ['Cairo', 'Alexandria', 'Giza', 'Luxor'],
    },
    {
      display: 'Ankara',
      accepted: ['Ankara'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of Turkey?',
      options: ['Ankara', 'Istanbul', 'Izmir', 'Bursa'],
    },
    {
      display: 'Pretoria',
      accepted: ['Pretoria'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of South Africa (the administrative/executive capital)?',
      options: ['Pretoria', 'Cape Town', 'Johannesburg', 'Durban'],
    },
    {
      display: 'Wellington',
      accepted: ['Wellington'],
      promptKind: 'TEXT',
      promptValue: 'What is the capital of New Zealand?',
      options: ['Wellington', 'Auckland', 'Christchurch', 'Hamilton'],
    },
  ],
};
