/** GENERATED by scripts/genQuizFixtures.ts — do not edit by hand. AI-authored
 * ORDER_UP quiz, committed so the seed is deterministic. Regenerate with
 * `AWS_PROFILE=personal npm run gen:quiz-fixtures`. DATA (gate-exempt). */
import type { QuizFixture } from './types';

export const orderUpQuiz: QuizFixture = {
  topic: 'Order these Space Race milestones (earliest first)',
  categorySlug: 'history',
  description: 'An AI-generated order up quiz.',
  mode: 'ORDER_UP',
  inputMode: 'ARRANGE',
  scoringMode: 'SEQUENCE',
  timeLimitSeconds: 120,
  answers: [
    {
      display: 'Sputnik 1 (first artificial satellite)',
      accepted: ['Sputnik 1 (first artificial satellite)', 'Sputnik 1', 'Sputnik', 'Sputnik I'],
      promptKind: 'NONE',
      orderIndex: 0,
    },
    {
      display: 'Laika (first animal to orbit Earth)',
      accepted: ['Laika (first animal to orbit Earth)', 'Laika', 'Sputnik 2', 'Laika the dog'],
      promptKind: 'NONE',
      orderIndex: 1,
    },
    {
      display: 'Yuri Gagarin (first human in space)',
      accepted: ['Yuri Gagarin (first human in space)', 'Yuri Gagarin', 'Gagarin', 'Vostok 1'],
      promptKind: 'NONE',
      orderIndex: 2,
    },
    {
      display: 'Valentina Tereshkova (first woman in space)',
      accepted: [
        'Valentina Tereshkova (first woman in space)',
        'Valentina Tereshkova',
        'Tereshkova',
        'Vostok 6',
      ],
      promptKind: 'NONE',
      orderIndex: 3,
    },
    {
      display: 'Alexei Leonov (first spacewalk)',
      accepted: [
        'Alexei Leonov (first spacewalk)',
        'Alexei Leonov',
        'Leonov',
        'Voskhod 2',
        'first spacewalk',
      ],
      promptKind: 'NONE',
      orderIndex: 4,
    },
    {
      display: 'Apollo 11 (first humans on the Moon)',
      accepted: [
        'Apollo 11 (first humans on the Moon)',
        'Apollo 11',
        'Moon landing',
        'Neil Armstrong',
        'first Moon landing',
      ],
      promptKind: 'NONE',
      orderIndex: 5,
    },
  ],
};
