/** GENERATED by scripts/genQuizFixtures.ts — do not edit by hand. AI-authored
 * SLIDESHOW quiz, committed so the seed is deterministic. Regenerate with
 * `AWS_PROFILE=personal npm run gen:quiz-fixtures`. DATA (gate-exempt). */
import type { QuizFixture } from './types';

export const slideshowQuiz: QuizFixture = {
  topic: 'Name the Artist from a Famous Album',
  categorySlug: 'music',
  description: 'An AI-generated slideshow quiz.',
  mode: 'SLIDESHOW',
  inputMode: 'TYPE',
  scoringMode: 'MEMBERSHIP',
  timeLimitSeconds: 120,
  answers: [
    {
      display: 'Pink Floyd',
      accepted: ['Pink Floyd'],
      promptKind: 'TEXT',
      promptValue: '"The Dark Side of the Moon" (1973)',
    },
    {
      display: 'Michael Jackson',
      accepted: ['Michael Jackson', 'MJ'],
      promptKind: 'TEXT',
      promptValue: '"Thriller" (1982)',
    },
    {
      display: 'AC/DC',
      accepted: ['AC/DC', 'ACDC', 'AC DC'],
      promptKind: 'TEXT',
      promptValue: '"Back in Black" (1980)',
    },
    {
      display: 'Fleetwood Mac',
      accepted: ['Fleetwood Mac'],
      promptKind: 'TEXT',
      promptValue: '"Rumours" (1977)',
    },
    {
      display: 'Nirvana',
      accepted: ['Nirvana'],
      promptKind: 'TEXT',
      promptValue: '"Nevermind" (1991)',
    },
    {
      display: 'Adele',
      accepted: ['Adele', 'Adele Adkins'],
      promptKind: 'TEXT',
      promptValue: '"21" (2011)',
    },
  ],
};
