/** GENERATED by scripts/genQuizFixtures.ts — do not edit by hand. AI-authored
 * SORTABLE quiz, committed so the seed is deterministic. Regenerate with
 * `AWS_PROFILE=personal npm run gen:quiz-fixtures`. DATA (gate-exempt). */
import type { QuizFixture } from './types';

export const sortableQuiz: QuizFixture = {
  topic: 'Fruit or Vegetable?',
  categorySlug: 'food',
  description: 'An AI-generated sortable quiz.',
  mode: 'SORTABLE',
  inputMode: 'ARRANGE',
  scoringMode: 'BUCKETING',
  timeLimitSeconds: 120,
  answers: [
    {
      display: 'Tomato',
      accepted: ['Tomato'],
      promptKind: 'NONE',
      bucket: 'Fruit',
    },
    {
      display: 'Cucumber',
      accepted: ['Cucumber'],
      promptKind: 'NONE',
      bucket: 'Fruit',
    },
    {
      display: 'Avocado',
      accepted: ['Avocado'],
      promptKind: 'NONE',
      bucket: 'Fruit',
    },
    {
      display: 'Bell Pepper',
      accepted: ['Bell Pepper'],
      promptKind: 'NONE',
      bucket: 'Fruit',
    },
    {
      display: 'Carrot',
      accepted: ['Carrot'],
      promptKind: 'NONE',
      bucket: 'Vegetable',
    },
    {
      display: 'Spinach',
      accepted: ['Spinach'],
      promptKind: 'NONE',
      bucket: 'Vegetable',
    },
    {
      display: 'Potato',
      accepted: ['Potato'],
      promptKind: 'NONE',
      bucket: 'Vegetable',
    },
    {
      display: 'Broccoli',
      accepted: ['Broccoli'],
      promptKind: 'NONE',
      bucket: 'Vegetable',
    },
  ],
};
