/** GENERATED by scripts/genAcrosticFixtures.ts — do not edit by hand. AI-authored
 * + engine-validated acrostic puzzles, committed so the seed is deterministic.
 * Regenerate: `AWS_PROFILE=personal npm run gen:acrostic-fixtures`. DATA. */
export interface AcrosticFixture {
  title: string;
  quote: string;
  author: string;
  clues: { clue: string; answer: string }[];
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
}

export const seedAcrostics: AcrosticFixture[] = [
  {
    title: 'Keep Going',
    quote: 'It does not matter how slowly you go as long as you do not stop.',
    author: 'Confucius',
    clues: [
      {
        clue: 'Frozen water',
        answer: 'ice',
      },
      {
        clue: 'A large, hoofed animal often ridden or used to pull carts',
        answer: 'horse',
      },
      {
        clue: 'The star at the center of our solar system',
        answer: 'sun',
      },
      {
        clue: 'A body of salt water larger than a sea',
        answer: 'ocean',
      },
      {
        clue: 'The opposite of night',
        answer: 'day',
      },
      {
        clue: 'A tall plant with a trunk and branches',
        answer: 'tree',
      },
    ],
    difficulty: 'EASY',
  },
  {
    title: 'The Spark of Wonder',
    quote: 'I have no special talent. I am only passionately curious.',
    author: 'Albert Einstein',
    clues: [
      {
        clue: 'The opposite of night',
        answer: 'day',
      },
      {
        clue: 'A color made by mixing blue and yellow',
        answer: 'green',
      },
      {
        clue: 'The star at the center of our solar system',
        answer: 'sun',
      },
      {
        clue: 'A large body of salt water',
        answer: 'ocean',
      },
      {
        clue: 'The season after winter',
        answer: 'spring',
      },
      {
        clue: 'A young dog',
        answer: 'puppy',
      },
    ],
    difficulty: 'MEDIUM',
  },
  {
    title: 'A Little Kindness',
    quote: 'No act of kindness, no matter how small, is ever wasted.',
    author: 'Aesop',
    clues: [
      {
        clue: 'The frozen form of water',
        answer: 'ice',
      },
      {
        clue: 'A large, powerful African cat known as the king of the jungle',
        answer: 'lion',
      },
      {
        clue: 'The opposite of night',
        answer: 'day',
      },
      {
        clue: 'A color made by mixing blue and yellow',
        answer: 'green',
      },
      {
        clue: 'The star at the center of our solar system',
        answer: 'sun',
      },
      {
        clue: 'A yellow fruit that monkeys are said to love',
        answer: 'banana',
      },
    ],
    difficulty: 'HARD',
  },
];
