/** GENERATED by scripts/genAcrosticFixtures.ts — do not edit by hand. AI-authored
 * + engine-validated acrostic puzzles, committed so the seed is deterministic.
 * Regenerate: `AWS_PROFILE=personal npm run gen:acrostic-fixtures`. DATA. */
export interface AcrosticFixture {
  title: string;
  quote: string;
  author: string;
  clues: { clue: string; answer: string }[];
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
}

export const seedAcrostics: AcrosticFixture[] = [
  {
    title: 'The Deep Blue',
    quote: 'The sea, once it casts its spell, holds one in its net of wonder forever.',
    author: 'Jacques Cousteau',
    clues: [
      {
        clue: 'A citrus fruit that is also a color',
        answer: 'orange',
      },
      {
        clue: 'A young cow',
        answer: 'calf',
      },
      {
        clue: 'A large gray mammal with a trunk',
        answer: 'elephant',
      },
      {
        clue: 'A red fruit often used in pies, or the color of it',
        answer: 'apple',
      },
      {
        clue: 'The opposite of day',
        answer: 'night',
      },
    ],
    difficulty: 'EASY',
  },
  {
    title: 'A Sense of Awe',
    quote: 'Wisdom begins in wonder.',
    author: 'Socrates',
    clues: [
      {
        clue: 'A large sea mammal, the largest animal ever known to have lived',
        answer: 'whale',
      },
      {
        clue: 'The fruit commonly associated with juice and the color of its skin',
        answer: 'orange',
      },
      {
        clue: 'The time of day when it is dark and the moon is out',
        answer: 'night',
      },
      {
        clue: 'A playful water-loving mammal known for using tools to open shellfish',
        answer: 'dolphin',
      },
      {
        clue: 'A large gray animal with a trunk and tusks',
        answer: 'elephant',
      },
      {
        clue: 'The colorful arc in the sky after rain',
        answer: 'rainbow',
      },
    ],
    difficulty: 'MEDIUM',
  },
  {
    title: 'Brave Heart',
    quote: 'Courage is not the absence of fear, but the triumph over it.',
    author: 'Nelson Mandela',
    clues: [
      {
        clue: 'A young feline animal',
        answer: 'cat',
      },
      {
        clue: 'The large body of salt water covering most of Earth',
        answer: 'ocean',
      },
      {
        clue: 'A single item of something, or the whole and complete quantity',
        answer: 'unit',
      },
      {
        clue: 'A bright band of colors seen in the sky after rain',
        answer: 'rainbow',
      },
      {
        clue: 'A red fruit that keeps the doctor away',
        answer: 'apple',
      },
      {
        clue: 'A large ape found in African forests',
        answer: 'gorilla',
      },
      {
        clue: 'A large gray mammal with a long trunk and tusks',
        answer: 'elephant',
      },
    ],
    difficulty: 'HARD',
  },
];
