/** GENERATED by scripts/genChessAttackFixtures.ts — do not edit by hand.
 * Real mate-in-N puzzles from the Lichess puzzle DB (CC0), each RE-VERIFIED with
 * chess.js to be a forced checkmate. `position` is a FEN; `solution` is the
 * solver's UCI line (defender replies auto-played). DATA (gate-exempt). */
import type { ChessFixture } from './chessType';

export const seedChessPuzzles: ChessFixture[] = [
  {
    name: 'Forced Mate (mate in 1)',
    position: '2kr1b1r/p1p2pp1/2pqN3/7p/6n1/2NPB3/PPP2PPP/R2Q1RK1 b - - 0 13',
    solution: '["d6h2"]',
    movesToWin: 1,
    difficulty: 'EASY',
  },
  {
    name: 'Find the Mate (mate in 1)',
    position: '6k1/p1p3pp/4N3/1p6/2q1r1n1/2B5/PP4PP/3R1R1K w - - 0 29',
    solution: '["f1f8"]',
    movesToWin: 1,
    difficulty: 'EASY',
  },
  {
    name: 'Forced Mate (mate in 2)',
    position: '4r3/1k6/pp3P2/1b5p/3R1p2/P1R2P2/1P4PP/6K1 b - - 0 35',
    solution: '["e8e1","g1f2","e1f1"]',
    movesToWin: 2,
    difficulty: 'MEDIUM',
  },
  {
    name: 'Find the Mate (mate in 2)',
    position: 'r1bq3r/pp1nbkp1/2p1p2p/8/2BP4/1PN3P1/P3QP1P/3R1RK1 w - - 0 20',
    solution: '["e2e6","f7f8","e6f7"]',
    movesToWin: 2,
    difficulty: 'MEDIUM',
  },
  {
    name: 'Forced Mate (mate in 3)',
    position: '6nr/p4p1p/k1p5/1p6/1QN5/2P1P3/4KPqP/8 w - - 0 27',
    solution: '["b4a5","a6b7","c4d6","b7b8","a5d8"]',
    movesToWin: 3,
    difficulty: 'HARD',
  },
  {
    name: 'Find the Mate (mate in 3)',
    position: '4rr1k/p1Qn2pp/3p1q2/8/8/2P5/PP3PPP/RN3RK1 b - - 0 16',
    solution: '["f6f2","f1f2","e8e1","f2f1","e1f1"]',
    movesToWin: 3,
    difficulty: 'HARD',
  },
];
