/** GENERATED by scripts/genChessAttackFixtures.ts — do not edit by hand.
 * AI-authored + engine-validated ChessAttack puzzles, committed so the seed is
 * deterministic. Each solution was replayed on the real play engine and proven
 * to capture the opposing king. Regenerate: `AWS_PROFILE=personal npm run
 * gen:chess-fixtures`. DATA (gate-exempt). */
import type { ChessFixture } from './chessType';

export const seedChessPuzzles: ChessFixture[] = [
  {
    name: "Rook's Reach",
    position:
      '{"size":5,"pieces":[{"sq":"a1","piece":"R","side":"w"},{"sq":"a5","piece":"K","side":"b"}],"toMove":"w","goal":"White to capture the black king in one move."}',
    solution: '["a1a5"]',
    movesToWin: 1,
    difficulty: 'EASY',
  },
  {
    name: "Rook's Double Strike",
    position:
      '{"size":5,"pieces":[{"sq":"a1","piece":"R","side":"w"},{"sq":"c3","piece":"P","side":"b"},{"sq":"e5","piece":"K","side":"b"}],"toMove":"w","goal":"White to capture the black king in 2 moves"}',
    solution: '["a1a5","a5e5"]',
    movesToWin: 2,
    difficulty: 'MEDIUM',
  },
  {
    name: 'The Silent March',
    position:
      '{"size":5,"pieces":[{"sq":"a1","piece":"R","side":"w"},{"sq":"b2","piece":"N","side":"w"},{"sq":"e5","piece":"K","side":"b"},{"sq":"e3","piece":"P","side":"b"}],"toMove":"w","goal":"White to capture the Black king in exactly 3 moves"}',
    solution: '["b2d3","a1a5","a5e5"]',
    movesToWin: 3,
    difficulty: 'HARD',
  },
];
