/** GENERATED by scripts/genQuizzleFixtures.ts — do not edit by hand. AI-authored
 * + validated wager quizzes, committed so the seed is deterministic.
 * Regenerate: `AWS_PROFILE=personal npm run gen:quizzle-fixtures`. DATA. */

export interface QuizzleQuestionFixture {
  question: string;
  answer: string;
  accepted?: string[];
}

export interface QuizzleFixture {
  topic: string;
  startingBank: number;
  questions: QuizzleQuestionFixture[];
}

export const seedQuizzles: QuizzleFixture[] = [
  {
    topic: 'World Geography',
    startingBank: 1000,
    questions: [
      {
        question: 'What is the longest river in the world?',
        answer: 'Nile',
        accepted: ['The Nile', 'Nile River'],
      },
      {
        question: 'Which is the largest country in the world by land area?',
        answer: 'Russia',
        accepted: ['Russian Federation'],
      },
      {
        question: 'What is the tallest mountain above sea level on Earth?',
        answer: 'Mount Everest',
        accepted: ['Everest'],
      },
      {
        question: 'Which desert is the largest hot desert in the world?',
        answer: 'Sahara',
        accepted: ['Sahara Desert'],
      },
      {
        question: 'What is the smallest country in the world by area?',
        answer: 'Vatican City',
        accepted: ['The Vatican', 'Holy See'],
      },
      {
        question: 'Which ocean is the largest and deepest on Earth?',
        answer: 'Pacific Ocean',
        accepted: ['Pacific', 'The Pacific'],
      },
      {
        question: 'What is the capital city of Australia?',
        answer: 'Canberra',
      },
      {
        question: 'On which continent is the Atacama Desert located?',
        answer: 'South America',
        accepted: ['S. America'],
      },
    ],
  },
  {
    topic: 'Science',
    startingBank: 1000,
    questions: [
      {
        question: 'What is the chemical symbol for gold?',
        answer: 'Au',
      },
      {
        question: 'What planet in our solar system is known as the Red Planet?',
        answer: 'Mars',
      },
      {
        question: 'What gas do plants primarily absorb from the atmosphere during photosynthesis?',
        answer: 'Carbon dioxide',
        accepted: ['CO2', 'CO₂'],
      },
      {
        question: 'What is the powerhouse of the cell, responsible for producing energy?',
        answer: 'Mitochondria',
        accepted: ['mitochondrion'],
      },
      {
        question: 'What is the speed of light in a vacuum, in kilometers per second (rounded)?',
        answer: '300,000 km/s',
        accepted: ['300000', '299792', '299,792', '299792 km/s', '300000 km/s', '299,792 km/s'],
      },
      {
        question: 'What force keeps planets in orbit around the Sun?',
        answer: 'Gravity',
        accepted: ['gravitation', 'gravitational force'],
      },
      {
        question: "What is the most abundant gas in Earth's atmosphere?",
        answer: 'Nitrogen',
        accepted: ['N2', 'N₂'],
      },
      {
        question: 'How many bones are in the adult human body?',
        answer: '206',
        accepted: ['two hundred and six'],
      },
    ],
  },
  {
    topic: 'Movies',
    startingBank: 1000,
    questions: [
      {
        question:
          'Which 1997 film directed by James Cameron won 11 Academy Awards, tying the record for most Oscars won by a single film?',
        answer: 'Titanic',
      },
      {
        question: "Who directed the 1994 crime film 'Pulp Fiction'?",
        answer: 'Quentin Tarantino',
        accepted: ['Tarantino'],
      },
      {
        question: "In the 'Star Wars' saga, what is the name of Han Solo's ship?",
        answer: 'Millennium Falcon',
        accepted: ['The Millennium Falcon'],
      },
      {
        question: "Which actor played the title character in the 1994 film 'Forrest Gump'?",
        answer: 'Tom Hanks',
        accepted: ['Hanks'],
      },
      {
        question:
          "What 2019 film became the highest-grossing movie of all time (unadjusted) upon its re-release, surpassing 'Avatar' at the time?",
        answer: 'Avengers: Endgame',
        accepted: ['Endgame', 'Avengers Endgame'],
      },
      {
        question: "Which animated 1994 Disney film features the song 'Circle of Life'?",
        answer: 'The Lion King',
        accepted: ['Lion King'],
      },
    ],
  },
];
