/**
 * Build-time acrostic fixture generator. Calls Bedrock with the SAME prompt the
 * game's generator uses, VALIDATES each candidate with validateAcrostic
 * (rejecting malformed/unsolvable ones + retrying), and writes the verified
 * puzzles to the committed seed fixture — so the seed stays deterministic (no
 * live LLM at seed time). Re-run: AWS_PROFILE=personal npm run gen:acrostic-fixtures
 * Not gated (scripts/, outside src/ + amplify/).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import {
  buildAcrosticRequest,
  type AcrosticRequest,
} from '../amplify/acrosticgen/shared/acrosticPrompt';
import { parseAcrosticGen } from '../amplify/acrosticgen/shared/parseAcrosticGen';
import { validateAcrostic } from '../amplify/acrosticgen/shared/validateAcrostic';
import type { AcrosticFixture } from '../amplify/seed/fixtures/acrostic';

const MODEL_ID = 'us.anthropic.claude-opus-4-8';
const client = new BedrockRuntimeClient({ region: 'us-west-2' });

const DIFFICULTIES: AcrosticFixture['difficulty'][] = ['EASY', 'MEDIUM', 'HARD'];

const JOBS: AcrosticRequest[] = [
  { topic: 'perseverance' },
  { topic: 'curiosity' },
  { topic: 'kindness' },
];

async function invoke(body: string): Promise<unknown> {
  const res = await client.send(
    new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body,
    }),
  );
  return JSON.parse(new TextDecoder().decode(res.body));
}

/** Generate + validate one acrostic, retrying until the LLM produces a valid one. */
async function genOne(
  req: AcrosticRequest,
  difficulty: AcrosticFixture['difficulty'],
  attempts = 4,
) {
  for (let i = 0; i < attempts; i++) {
    try {
      const body = await invoke(buildAcrosticRequest(req));
      const v = validateAcrostic(parseAcrosticGen(body as Parameters<typeof parseAcrosticGen>[0]));
      if (v.ok && v.acrostic) return { ...v.acrostic, difficulty };
      console.log(`  retry (${req.topic}): ${v.reason}`);
    } catch (e) {
      console.log(`  retry (${req.topic}): ${e instanceof Error ? e.message : e}`);
    }
  }
  throw new Error(`could not generate a valid acrostic about ${req.topic}`);
}

async function main() {
  const acrostics: AcrosticFixture[] = [];
  for (let i = 0; i < JOBS.length; i++) {
    const a = await genOne(JOBS[i], DIFFICULTIES[i % DIFFICULTIES.length]);
    acrostics.push(a);
    console.log(`${a.difficulty}: "${a.quote}" — ${a.author} (${a.clues.length} clues)`);
  }
  const banner = `/** GENERATED by scripts/genAcrosticFixtures.ts — do not edit by hand. AI-authored
 * + engine-validated acrostic puzzles, committed so the seed is deterministic.
 * Regenerate: \`AWS_PROFILE=personal npm run gen:acrostic-fixtures\`. DATA. */
export interface AcrosticFixture {
  title: string;
  quote: string;
  author: string;
  clues: { clue: string; answer: string }[];
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
}

export const seedAcrostics: AcrosticFixture[] = ${JSON.stringify(acrostics, null, 2)};
`;
  const out = join(process.cwd(), 'amplify/seed/fixtures/acrostic.ts');
  writeFileSync(out, banner);
  console.log(`Wrote ${acrostics.length} acrostics to ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
