/**
 * Build-time ChessAttack fixture generator. Calls Bedrock with the SAME prompt
 * the game's generator uses, INDEPENDENTLY VALIDATES each candidate with
 * validateChess (replaying the solution on the real play engine, rejecting any
 * that don't legally reach a king capture + retrying), and writes the verified
 * puzzles to the committed seed fixture — so the seed stays deterministic (no
 * live LLM at seed time). Re-run: AWS_PROFILE=personal npm run gen:chess-fixtures
 * Not gated (scripts/, outside src/ + amplify/).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import { buildChessRequest, type ChessRequest } from '../amplify/chessgen/shared/chessPrompt';
import { parseChessGen } from '../amplify/chessgen/shared/parseChessGen';
import { validateChess } from '../amplify/chessgen/shared/validateChess';
import type { ChessFixture } from '../amplify/seed/fixtures/chessType';

const MODEL_ID = 'us.anthropic.claude-opus-4-8';
const client = new BedrockRuntimeClient({ region: 'us-west-2' });

const JOBS: ChessRequest[] = [
  { difficulty: 'EASY' },
  { difficulty: 'MEDIUM' },
  { difficulty: 'HARD' },
];

async function invoke(body: string): Promise<unknown> {
  const res = await client.send(
    new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body,
    }),
  );
  return JSON.parse(new TextDecoder().decode(res.body));
}

/** Generate + validate one puzzle, retrying until the LLM produces a valid one. */
async function genOne(req: ChessRequest, attempts = 4): Promise<ChessFixture> {
  for (let i = 0; i < attempts; i++) {
    try {
      const body = await invoke(buildChessRequest(req));
      const v = validateChess(parseChessGen(body as Parameters<typeof parseChessGen>[0]));
      if (v.ok && v.puzzle) {
        return {
          name: v.puzzle.name,
          position: JSON.stringify(v.puzzle.position),
          solution: JSON.stringify(v.puzzle.solution),
          movesToWin: v.puzzle.movesToWin,
          difficulty: req.difficulty,
        };
      }
      console.log(`  retry (${req.difficulty}): ${v.reason}`);
    } catch (e) {
      console.log(`  retry (${req.difficulty}): ${e instanceof Error ? e.message : e}`);
    }
  }
  throw new Error(`could not generate a valid ${req.difficulty} ChessAttack puzzle`);
}

async function main() {
  const puzzles: ChessFixture[] = [];
  for (const req of JOBS) {
    const p = await genOne(req);
    puzzles.push(p);
    console.log(`${p.difficulty}: ${p.name} (${p.movesToWin} moves)`);
  }
  const banner = `/** GENERATED by scripts/genChessAttackFixtures.ts — do not edit by hand.
 * AI-authored + engine-validated ChessAttack puzzles, committed so the seed is
 * deterministic. Each solution was replayed on the real play engine and proven
 * to capture the opposing king. Regenerate: \`AWS_PROFILE=personal npm run
 * gen:chess-fixtures\`. DATA (gate-exempt). */
import type { ChessFixture } from './chessType';

export const seedChessPuzzles: ChessFixture[] = ${JSON.stringify(puzzles, null, 2)};
`;
  const out = join(process.cwd(), 'amplify/seed/fixtures/chess.ts');
  writeFileSync(out, banner);
  console.log(`Wrote ${puzzles.length} puzzles to ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
