/**
 * Build the ChessAttack fixture from the Lichess puzzle DB (CC0). Lichess format:
 * the FEN is the position BEFORE a setup move; the first UCI in `Moves` is that
 * setup (opponent) move, and the solver plays from move 2. We apply the setup
 * move to get the real START fen, then the remaining line is the solver's forced
 * mate — which we RE-VERIFY with chess.js (verifyMate) before baking. Picks a
 * graded spread (mate-in-1 EASY, -2 MEDIUM, -3 HARD).
 *
 * Fetch the source once (streamed + filtered, ~a few MB, not the full 300MB):
 *   curl -s https://database.lichess.org/lichess_db_puzzle.csv.zst | zstd -dc \
 *     | grep -E "mateIn[123]" | head -400 > /tmp/mates.csv
 * Then: npx tsx scripts/genChessAttackFixtures.ts   (reads /tmp/mates.csv)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { Chess } from 'chess.js';
import { verifyMate } from '../amplify/chessgen/shared/verifyMate';
import type { ChessFixture } from '../amplify/seed/fixtures/chessType';

interface Row {
  fen: string;
  line: string[];
  themes: string;
}

function parse(csv: string): Row[] {
  return csv
    .trim()
    .split('\n')
    .map((l) => l.split(','))
    .filter((c) => c.length >= 8)
    .map((c) => ({ fen: c[1], line: c[2].split(' '), themes: c[7] }));
}

/** Apply Lichess's setup move → the real start fen + the solver's line. */
function toPuzzle(row: Row): { fen: string; line: string[] } | null {
  const g = new Chess(row.fen);
  const s = row.line[0];
  try {
    if (!g.move({ from: s.slice(0, 2), to: s.slice(2, 4), promotion: s.slice(4) || undefined }))
      return null;
  } catch {
    return null;
  }
  return { fen: g.fen(), line: row.line.slice(1) };
}

const TITLES = ['Forced Mate', 'Find the Mate', 'Checkmate!', 'Deliver Mate', 'Mating Net'];
const DIFF: Record<number, ChessFixture['difficulty']> = { 1: 'EASY', 2: 'MEDIUM', 3: 'HARD' };

function pick(rows: Row[], mateN: number, count: number): ChessFixture[] {
  const out: ChessFixture[] = [];
  for (const row of rows) {
    if (out.length >= count) break;
    if (!row.themes.includes(`mateIn${mateN}`)) continue;
    const p = toPuzzle(row);
    if (!p) continue;
    const v = verifyMate({ name: 'x', fen: p.fen, line: p.line, difficulty: DIFF[mateN] });
    if (!v.ok || v.puzzle?.movesToWin !== mateN) continue;
    out.push({
      name: `${TITLES[out.length % TITLES.length]} (mate in ${mateN})`,
      position: p.fen, // FEN — the new play engine reads FEN, not the old JSON board
      solution: JSON.stringify(p.line),
      movesToWin: mateN,
      difficulty: DIFF[mateN],
    });
  }
  return out;
}

const rows = parse(readFileSync('/tmp/mates.csv', 'utf8'));
const puzzles = [...pick(rows, 1, 2), ...pick(rows, 2, 2), ...pick(rows, 3, 2)];
const banner = `/** GENERATED by scripts/genChessAttackFixtures.ts — do not edit by hand.
 * Real mate-in-N puzzles from the Lichess puzzle DB (CC0), each RE-VERIFIED with
 * chess.js to be a forced checkmate. \`position\` is a FEN; \`solution\` is the
 * solver's UCI line (defender replies auto-played). DATA (gate-exempt). */
import type { ChessFixture } from './chessType';

export const seedChessPuzzles: ChessFixture[] = ${JSON.stringify(puzzles, null, 2)};
`;
writeFileSync('amplify/seed/fixtures/chess.ts', banner);
console.log(
  `Wrote ${puzzles.length} verified puzzles (mate-in: ${puzzles.map((p) => p.movesToWin).join(',')}).`,
);
