/**
 * Build-time word-ladder fixture generator. Calls Bedrock with the SAME prompt
 * the game's generator uses, VALIDATES each candidate with validateLadder
 * (rejecting unsolvable ones + retrying), and writes the verified ladders to the
 * committed seed fixture — so the seed stays deterministic (no live LLM at seed
 * time). Re-run: AWS_PROFILE=personal npm run gen:ladder-fixtures
 * Not gated (scripts/, outside src/ + amplify/).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import { buildLadderRequest, type LadderRequest } from '../amplify/laddergen/shared/ladderPrompt';
import { parseLadderGen } from '../amplify/laddergen/shared/parseLadderGen';
import { validateLadder } from '../amplify/laddergen/shared/validateLadder';

const MODEL_ID = 'us.anthropic.claude-opus-4-8';
const client = new BedrockRuntimeClient({ region: 'us-west-2' });

const JOBS: LadderRequest[] = [
  { length: 3, difficulty: 'EASY' },
  { length: 4, difficulty: 'MEDIUM' },
  { length: 4, difficulty: 'HARD' },
];

async function invoke(body: string): Promise<unknown> {
  const res = await client.send(
    new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body,
    }),
  );
  return JSON.parse(new TextDecoder().decode(res.body));
}

/** Generate + validate one ladder, retrying until the LLM produces a valid one. */
async function genOne(req: LadderRequest, attempts = 4) {
  for (let i = 0; i < attempts; i++) {
    try {
      const body = await invoke(buildLadderRequest(req));
      const v = validateLadder(parseLadderGen(body as Parameters<typeof parseLadderGen>[0]));
      if (v.ok && v.ladder) return { ...v.ladder, difficulty: req.difficulty };
      console.log(`  retry (${req.difficulty} ${req.length}): ${v.reason}`);
    } catch (e) {
      console.log(`  retry (${req.difficulty}): ${e instanceof Error ? e.message : e}`);
    }
  }
  throw new Error(`could not generate a valid ${req.difficulty} ${req.length}-letter ladder`);
}

async function main() {
  const ladders = [];
  for (const req of JOBS) {
    const l = await genOne(req);
    ladders.push(l);
    console.log(`${l.difficulty}: ${l.start} → ${l.target} (${l.parPath.length - 1} steps)`);
  }
  const banner = `/** GENERATED by scripts/genLadderFixtures.ts — do not edit by hand. AI-authored
 * + engine-validated word ladders, committed so the seed is deterministic.
 * Regenerate: \`AWS_PROFILE=personal npm run gen:ladder-fixtures\`. DATA. */
import type { LadderFixture } from './laddersType';

export const seedLadders: LadderFixture[] = ${JSON.stringify(ladders, null, 2)};
`;
  const out = join(process.cwd(), 'amplify/seed/fixtures/ladders.ts');
  writeFileSync(out, banner);
  console.log(`Wrote ${ladders.length} ladders to ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
