/**
 * Build-time generator for the world-countries map template. Reconciles the
 * world-atlas topology with the canonical ISO country table + curated alias
 * overrides ONCE, emitting a typed fixture (amplify/quizgen/fixtures/
 * worldCountries.ts) that the quizgen Lambda reads at runtime. This keeps the
 * heavy reference packages (world-atlas, topojson-client, i18n-iso-countries)
 * as build-time-only devDependencies — neither the Lambda nor the play client
 * bundles them. Re-run with `npm run gen:map-template` if the sources change.
 *
 * Not covered by the quality gates (lives in scripts/, outside src/ + amplify/).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import topo from 'world-atlas/countries-110m.json' assert { type: 'json' };
import { feature } from 'topojson-client';
import countries from 'i18n-iso-countries';
import enLocale from 'i18n-iso-countries/langs/en.json' assert { type: 'json' };
import {
  buildMapAnswers,
  type TopologyRegion,
  type IsoResolvers,
} from '../amplify/quizgen/shared/buildMapAnswers';
import { COUNTRY_ALIAS_OVERRIDES } from '../amplify/quizgen/fixtures/countryAliases';

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- topojson JSON is untyped
countries.registerLocale(enLocale as any);

/** Minimal shape of a topojson feature we read (id + properties.name). */
interface TopoFeature {
  id?: string | number;
  properties?: { name?: string };
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- topojson JSON is untyped
const fc = feature(topo as any, (topo as any).objects.countries) as { features: TopoFeature[] };
const regions: TopologyRegion[] = fc.features.map((f) => ({
  id: f.id != null ? String(f.id) : '',
  name: f.properties?.name ?? '',
}));

const iso: IsoResolvers = {
  namesForNumeric: (n) => {
    const a2 = countries.numericToAlpha2(n);
    if (!a2) return [];
    const all = countries.getName(a2, 'en', { select: 'all' });
    return Array.isArray(all) ? all : all ? [all] : [];
  },
  alpha2ForNumeric: (n) => countries.numericToAlpha2(n) ?? null,
  alpha3ForNumeric: (n) => {
    const a2 = countries.numericToAlpha2(n);
    return a2 ? (countries.alpha2ToAlpha3(a2) ?? null) : null;
  },
};

const answers = buildMapAnswers(regions, iso, COUNTRY_ALIAS_OVERRIDES);

const banner = `/**
 * GENERATED by scripts/genMapTemplate.ts — do not edit by hand.
 * The reconciled world-countries answer set (topology ↔ ISO ↔ aliases). DATA.
 * Regenerate with \`npm run gen:map-template\`.
 */
import type { MapAnswer } from '../shared/buildMapAnswers';

export const WORLD_COUNTRIES: MapAnswer[] = ${JSON.stringify(answers, null, 2)};
`;

const out = join(process.cwd(), 'amplify/quizgen/fixtures/worldCountries.ts');
writeFileSync(out, banner);
console.log(`Wrote ${answers.length} answers to ${out}`);
