/**
 * Build-time generator for the PICTURE_BOX seed: draw one AI image per subject
 * (Bedrock Stability), shrink to WebP (sharp), upload to the permanent files.jpc.io
 * image host, and write the reconciled fixture (subject + accepted spellings +
 * permanent image URL) to amplify/quizgen/fixtures/pictureBoxImages.ts.
 *
 * Landmarks (not real people): Stability draws them beautifully AND they're
 * instantly recognizable, so the played quiz shows real, guessable AI art rather
 * than emoji stand-ins. Run once with editor AWS creds:
 *   AWS_PROFILE=personal npx tsx scripts/genPictureBox.ts
 * Idempotent-ish: re-running redraws + re-uploads under fresh hashes.
 */
import { randomBytes } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { generateImage } from '../amplify/deckgen/shared/bedrock';
import { resizeWebp, CARD_IMAGE_SIZE } from '../amplify/deckgen/shared/resizeImage';

const HOST_BUCKET = 'amplify-d1wnjkkkrwiiql-mai-imagehostbucketaac3bfe7-aark0f5h8nw8';
const REGION = 'us-west-2';
const s3 = new S3Client({ region: REGION });

interface Subject {
  display: string;
  accepted: string[];
  hint: string;
  prompt: string;
}

const SUBJECTS: Subject[] = [
  {
    display: 'Eiffel Tower',
    accepted: ['eiffel tower', 'eiffel', 'la tour eiffel'],
    hint: 'Paris, France',
    prompt: 'The Eiffel Tower in Paris on a clear day',
  },
  {
    display: 'Statue of Liberty',
    accepted: ['statue of liberty', 'lady liberty', 'liberty'],
    hint: 'New York, USA',
    prompt: 'The Statue of Liberty on Liberty Island',
  },
  {
    display: 'Taj Mahal',
    accepted: ['taj mahal', 'taj'],
    hint: 'Agra, India',
    prompt: 'The Taj Mahal with its reflecting pool',
  },
  {
    display: 'Great Wall of China',
    accepted: ['great wall of china', 'great wall', 'the great wall'],
    hint: 'China',
    prompt: 'The Great Wall of China winding over green mountains',
  },
  {
    display: 'Colosseum',
    accepted: ['colosseum', 'coliseum', 'roman colosseum'],
    hint: 'Rome, Italy',
    prompt: 'The Roman Colosseum exterior',
  },
  {
    display: 'Sydney Opera House',
    accepted: ['sydney opera house', 'opera house'],
    hint: 'Sydney, Australia',
    prompt: 'The Sydney Opera House by the harbour',
  },
];

async function uploadImage(webp: Uint8Array, display: string): Promise<string> {
  const slug = display.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const hash = randomBytes(3).toString('hex');
  const name = `${hash}-${slug}.webp`;
  await s3.send(
    new PutObjectCommand({
      Bucket: HOST_BUCKET,
      Key: `public/public/${name}`,
      Body: Buffer.from(webp),
      ContentType: 'image/webp',
    }),
  );
  return `https://files.jpc.io/d/${name}`;
}

async function main(): Promise<void> {
  const rows: Array<Subject & { image: string }> = [];
  for (const s of SUBJECTS) {
    process.stdout.write(`Drawing ${s.display}… `);
    const raw = await generateImage(
      `${s.prompt}. Photorealistic, vibrant, centered, no text, no words, no watermark.`,
    );
    const webp = await resizeWebp(raw, CARD_IMAGE_SIZE);
    const image = await uploadImage(webp, s.display);
    rows.push({ ...s, image });
    console.log(image);
  }

  const file = `/**
 * GENERATED by scripts/genPictureBox.ts — do not edit by hand.
 * AI-drawn landmark images (Bedrock Stability) hosted permanently on files.jpc.io.
 * Regenerate with \`AWS_PROFILE=personal npx tsx scripts/genPictureBox.ts\`. DATA.
 */
export interface PictureBoxSubject {
  display: string;
  accepted: string[];
  hint: string;
  image: string;
}

export const PICTURE_BOX_SUBJECTS: PictureBoxSubject[] = ${JSON.stringify(
    rows.map(({ display, accepted, hint, image }) => ({ display, accepted, hint, image })),
    null,
    2,
  )};
`;
  const out = 'amplify/quizgen/fixtures/pictureBoxImages.ts';
  writeFileSync(out, file);
  console.log(`\nWrote ${rows.length} subjects → ${out}`);
}

void main();
