/**
 * Build-time quiz-fixture generator. Runs the SAME prompt+parser the Lambda uses
 * (answersPrompt + parseAnswers) against Bedrock locally, and writes the result
 * as committed seed fixtures (amplify/seed/fixtures/quizzes/<key>.ts). This keeps
 * the sandbox seed DETERMINISTIC — a known set of AI-authored quizzes — with no
 * live LLM call during `npm run seed` or e2e. Re-run to refresh:
 *   AWS_PROFILE=personal npm run gen:quiz-fixtures
 *
 * Text modes only (CLASSIC/MULTIPLE_CHOICE/SLIDESHOW/SORTABLE/ORDER_UP). Picture
 * modes need image assets, so their fixtures stay hand-authored. Not gated
 * (lives in scripts/, outside src/ + amplify/).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import { buildAnswersRequest, type GenMode } from '../amplify/quizgen/shared/answersPrompt';
import { parseAnswers, type ParsedAnswer } from '../amplify/quizgen/shared/parseAnswers';
import { axesFor } from '../amplify/quizgen/shared/modeAxes';

const MODEL_ID = 'us.anthropic.claude-opus-4-8';
const client = new BedrockRuntimeClient({ region: 'us-west-2' });

// key | mode | topic | categorySlug | count
const JOBS: [string, GenMode, string, string, number][] = [
  ['classic', 'CLASSIC', 'US Presidents of the 2000s', 'history', 6],
  ['multipleChoice', 'MULTIPLE_CHOICE', 'World Capitals', 'geography', 8],
  ['slideshow', 'SLIDESHOW', 'Name the Artist from a Famous Album', 'music', 6],
  ['sortable', 'SORTABLE', 'Fruit or Vegetable?', 'food', 8],
  ['orderUp', 'ORDER_UP', 'Order these Space Race milestones (earliest first)', 'history', 6],
];

async function invoke(body: string): Promise<unknown> {
  const res = await client.send(
    new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body,
    }),
  );
  return JSON.parse(new TextDecoder().decode(res.body));
}

/** Render a fixture module from generated answers. */
function render(
  key: string,
  mode: GenMode,
  topic: string,
  slug: string,
  answers: ParsedAnswer[],
): string {
  const axes = axesFor(mode);
  const rows = answers.map((a) => ({
    display: a.display,
    accepted: a.accepted,
    promptKind: a.promptKind,
    ...(a.promptValue ? { promptValue: a.promptValue } : {}),
    ...(a.options ? { options: a.options } : {}),
    ...(a.orderIndex !== undefined ? { orderIndex: a.orderIndex } : {}),
    ...(a.bucket ? { bucket: a.bucket } : {}),
  }));
  return `/** GENERATED by scripts/genQuizFixtures.ts — do not edit by hand. AI-authored
 * ${mode} quiz, committed so the seed is deterministic. Regenerate with
 * \`AWS_PROFILE=personal npm run gen:quiz-fixtures\`. DATA (gate-exempt). */
import type { QuizFixture } from './types';

export const ${key}Quiz: QuizFixture = {
  topic: ${JSON.stringify(topic)},
  categorySlug: ${JSON.stringify(slug)},
  description: ${JSON.stringify(`An AI-generated ${mode.toLowerCase().replace('_', ' ')} quiz.`)},
  mode: ${JSON.stringify(mode)},
  inputMode: ${JSON.stringify(axes.inputMode)},
  scoringMode: ${JSON.stringify(axes.scoringMode)},
  timeLimitSeconds: 120,
  answers: ${JSON.stringify(rows, null, 2)},
};
`;
}

async function main() {
  for (const [key, mode, topic, slug, count] of JOBS) {
    const body = await invoke(buildAnswersRequest({ mode, topic, answerCount: count }));
    const answers = parseAnswers(mode, body as Parameters<typeof parseAnswers>[1]);
    const out = join(process.cwd(), `amplify/seed/fixtures/quizzes/${key}.ts`);
    writeFileSync(out, render(key, mode, topic, slug, answers));
    console.log(`${key}: ${answers.length} answers → ${out}`);
  }
  console.log('Done. Review the diff, then commit the regenerated fixtures.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
