/**
 * Build-time Quizzle fixture generator. Calls Bedrock with the SAME prompt the
 * game's generator uses, VALIDATES each candidate with validateQuizzle
 * (rejecting malformed ones + retrying), and writes the verified quizzes to the
 * committed seed fixture — so the seed stays deterministic (no live LLM at seed
 * time). Re-run: AWS_PROFILE=personal npm run gen:quizzle-fixtures
 * Not gated (scripts/, outside src/ + amplify/).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import {
  buildQuizzleRequest,
  type QuizzleRequest,
} from '../amplify/quizzlegen/shared/quizzlePrompt';
import { parseQuizzleGen } from '../amplify/quizzlegen/shared/parseQuizzleGen';
import { validateQuizzle } from '../amplify/quizzlegen/shared/validateQuizzle';
import type { QuizzleFixture } from '../amplify/seed/fixtures/quizzle';

const MODEL_ID = 'us.anthropic.claude-opus-4-8';
const STARTING_BANK = 1000;
const client = new BedrockRuntimeClient({ region: 'us-west-2' });

const JOBS: QuizzleRequest[] = [
  { topic: 'World Geography' },
  { topic: 'Science' },
  { topic: 'Movies' },
];

async function invoke(body: string): Promise<unknown> {
  const res = await client.send(
    new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body,
    }),
  );
  return JSON.parse(new TextDecoder().decode(res.body));
}

/** Generate + validate one quiz, retrying until the LLM produces a valid one. */
async function genOne(req: QuizzleRequest, attempts = 4): Promise<QuizzleFixture> {
  for (let i = 0; i < attempts; i++) {
    try {
      const body = await invoke(buildQuizzleRequest(req));
      const v = validateQuizzle(parseQuizzleGen(body as Parameters<typeof parseQuizzleGen>[0]));
      if (v.ok && v.quizzle) {
        const questions = v.quizzle.questions.map((q) => ({
          question: q.question,
          answer: q.answer,
          ...(q.accepted.length ? { accepted: q.accepted } : {}),
        }));
        return { topic: v.quizzle.topic, startingBank: STARTING_BANK, questions };
      }
      console.log(`  retry (${req.topic}): ${v.reason}`);
    } catch (e) {
      console.log(`  retry (${req.topic}): ${e instanceof Error ? e.message : e}`);
    }
  }
  throw new Error(`could not generate a valid quiz for "${req.topic}"`);
}

async function main() {
  const quizzes: QuizzleFixture[] = [];
  for (const req of JOBS) {
    const quiz = await genOne(req);
    quizzes.push(quiz);
    console.log(`${quiz.topic}: ${quiz.questions.length} questions`);
  }
  const banner = `/** GENERATED by scripts/genQuizzleFixtures.ts — do not edit by hand. AI-authored
 * + validated wager quizzes, committed so the seed is deterministic.
 * Regenerate: \`AWS_PROFILE=personal npm run gen:quizzle-fixtures\`. DATA. */

export interface QuizzleQuestionFixture {
  question: string;
  answer: string;
  accepted?: string[];
}

export interface QuizzleFixture {
  topic: string;
  startingBank: number;
  questions: QuizzleQuestionFixture[];
}

export const seedQuizzles: QuizzleFixture[] = ${JSON.stringify(quizzes, null, 2)};
`;
  const out = join(process.cwd(), 'amplify/seed/fixtures/quizzle.ts');
  writeFileSync(out, banner);
  console.log(`Wrote ${quizzes.length} quizzes to ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
