/**
 * Build-time Spelling Bee fixture generator. Uses an-array-of-english-words to
 * find valid 7-letter sets with pangrams, avoiding 's' (NYT convention), and
 * emits committed fixture data for deterministic seeding. Re-run:
 * npm run gen:spellingbee-fixtures
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import words from 'an-array-of-english-words';

interface BeeFixture {
  letters: string;
  centerLetter: string;
  answers: string[];
  pangrams: string[];
}

/** Build dictionary: ≥4 letters, lowercase, a-z only. */
const dict = words
  .filter((w: string) => w.length >= 4 && /^[a-z]+$/.test(w))
  .map((w: string) => w.toLowerCase());

/** Get unique letters in a word. */
function uniqueLetters(word: string): Set<string> {
  return new Set(word.split(''));
}

/** Find all words using only these letters, ≥4 chars, containing center. */
function findAnswers(letters: Set<string>, center: string): string[] {
  return dict.filter((w) => {
    if (!w.includes(center)) return false;
    for (const c of w) {
      if (!letters.has(c)) return false;
    }
    return true;
  });
}

/** Generate one board from a pangram candidate. */
function genBoard(pangram: string, center: string): BeeFixture | null {
  const letters = uniqueLetters(pangram);
  if (letters.size !== 7 || !letters.has(center)) return null;
  const answers = findAnswers(letters, center);
  if (answers.length < 20 || answers.length > 60) return null; // reasonable range
  const pangrams = answers.filter((w) => uniqueLetters(w).size === 7);
  if (pangrams.length === 0) return null;
  return {
    letters: Array.from(letters).sort().join(''),
    centerLetter: center,
    answers,
    pangrams,
  };
}

/** Find pangram candidates (exactly 7 distinct letters, no 's'). */
function findPangramCandidates(limit = 500): string[] {
  const candidates: string[] = [];
  for (const w of dict) {
    if (w.includes('s')) continue;
    const u = uniqueLetters(w);
    if (u.size === 7) {
      candidates.push(w);
      if (candidates.length >= limit) break;
    }
  }
  return candidates;
}

async function main() {
  console.log('Finding pangram candidates...');
  const candidates = findPangramCandidates();
  console.log(`Found ${candidates.length} pangram candidates.`);

  const boards: BeeFixture[] = [];
  const target = 30; // generate 30 boards for daily variety

  // Try to find boards with different center letters for variety
  for (const pangram of candidates) {
    if (boards.length >= target) break;
    const letters = Array.from(uniqueLetters(pangram));
    // Try each letter as center
    for (const center of letters) {
      if (boards.length >= target) break;
      const board = genBoard(pangram, center);
      if (board) {
        boards.push(board);
        console.log(
          `${boards.length}. ${board.letters} (center: ${board.centerLetter}) — ${board.answers.length} answers, ${board.pangrams.length} pangrams`,
        );
        break; // one board per pangram
      }
    }
  }

  if (boards.length === 0) {
    throw new Error('Could not generate any valid boards.');
  }

  // Sort first board deterministically for e2e (pick one with common words)
  boards.sort((a, b) => {
    // Prefer boards with 'e' or 'a' as center (common vowels)
    const aScore = ['e', 'a', 'i', 'o'].includes(a.centerLetter) ? 0 : 1;
    const bScore = ['e', 'a', 'i', 'o'].includes(b.centerLetter) ? 0 : 1;
    return aScore - bScore;
  });

  const banner = `/** GENERATED by scripts/genSpellingBeeFixtures.ts — do not edit by hand.
 * Dictionary-derived Spelling Bee boards, committed for deterministic seeding.
 * Regenerate: \`npm run gen:spellingbee-fixtures\`. DATA. */
import type { BeeFixture } from './spellingBeeType';

export const seedBees: BeeFixture[] = ${JSON.stringify(boards, null, 2)};
`;
  const out = join(process.cwd(), 'amplify/seed/fixtures/spellingBee.ts');
  writeFileSync(out, banner);
  console.log(`\nWrote ${boards.length} boards to ${out}`);
  console.log(
    `First board (for e2e): letters=${boards[0].letters}, center=${boards[0].centerLetter}, sample answer: ${boards[0].answers[0]}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
