/**
 * Build-time generator for the US-states map answer set (the "Find the State"
 * clickable game). Reads the us-atlas states topology (feature id = FIPS code,
 * name in properties), keeps the 50 states (drops DC + territories, FIPS >= 60),
 * and emits a MapAnswer[] whose promptValue is the FIPS id — matching the
 * states-10m topology feature id the renderer draws. Regenerate with
 * `npm run gen:state-map`. DATA (gate-exempt).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import states from 'us-atlas/states-10m.json' assert { type: 'json' };

interface Geom {
  id: string;
  properties: { name: string };
}
const geometries = (states as { objects: { states: { geometries: Geom[] } } }).objects.states
  .geometries;

// Common abbreviations / alternates so a typed guess (if ever reused for typing)
// or display stays forgiving. The click game only needs display; accepted covers
// the state name + its USPS code.
const USPS: Record<string, string> = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

const answers = geometries
  .filter((g) => Number(g.id) < 60) // 50 states + DC (11); territories are >= 60
  .filter((g) => g.properties.name !== 'District of Columbia') // 50 states only
  .sort((a, b) => a.properties.name.localeCompare(b.properties.name))
  .map((g, i) => {
    const name = g.properties.name;
    const usps = USPS[name];
    if (!usps) {
      console.error(`No USPS code for "${name}" — add it to the table.`);
      process.exit(1);
    }
    return {
      ord: i,
      promptKind: 'REGION' as const,
      promptValue: g.id,
      display: name,
      accepted: [name, usps],
    };
  });

if (answers.length !== 50) {
  console.error(`Expected 50 states, got ${answers.length}`);
  process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../amplify/quizgen/fixtures/usStates.ts');
writeFileSync(
  out,
  `/**
 * GENERATED by scripts/genStateMap.ts — do not edit by hand. The 50 US states
 * as map answers (promptValue = FIPS id, matching us-atlas states-10m). DATA.
 */
import type { MapAnswer } from '../shared/buildMapAnswers';

export const US_STATES: MapAnswer[] = ${JSON.stringify(answers, null, 2)};
`,
);
console.log(`Wrote ${out}: ${answers.length} states`);
